-- Generated by drizzle-kit, with one hand edit: the two UNIQUE constraints are moved
-- above the foreign keys that reference them (drizzle-kit emitted them after, which
-- Postgres refuses). Expand only: nothing is dropped except the notification_kind
-- enum, which the text column replaces; code from the previous deploy reads and
-- writes the same strings, and every value it writes passes the new CHECK.
ALTER TABLE "expenses" ADD CONSTRAINT "expenses_trip_id_uq" UNIQUE("trip_id","id");--> statement-breakpoint
ALTER TABLE "settlements" ADD CONSTRAINT "settlements_trip_id_uq" UNIQUE("trip_id","id");--> statement-breakpoint
ALTER TABLE "notifications" ALTER COLUMN "kind" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "notifications" ADD COLUMN "shopping_item_id" integer;--> statement-breakpoint
ALTER TABLE "notifications" ADD COLUMN "expense_id" integer;--> statement-breakpoint
ALTER TABLE "notifications" ADD COLUMN "settlement_id" integer;--> statement-breakpoint
ALTER TABLE "notifications" ADD COLUMN "thread_key" text;--> statement-breakpoint
ALTER TABLE "notifications" ADD COLUMN "data" jsonb;--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_shopping_item_fk" FOREIGN KEY ("trip_id","shopping_item_id") REFERENCES "public"."shopping_items"("trip_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_expense_fk" FOREIGN KEY ("trip_id","expense_id") REFERENCES "public"."expenses"("trip_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_settlement_fk" FOREIGN KEY ("trip_id","settlement_id") REFERENCES "public"."settlements"("trip_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "notifications_unread_idx" ON "notifications" USING btree ("user_id","trip_id","thread_key") WHERE "notifications"."read_at" is null;--> statement-breakpoint
CREATE UNIQUE INDEX "notifications_mention_uq" ON "notifications" USING btree ("comment_id","user_id") WHERE "notifications"."kind" = 'mention';--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_kind_ck" CHECK ("notifications"."kind" in ('mention', 'message', 'covered', 'uncovered', 'gear_added', 'shopping_added', 'bought', 'expense_added', 'expense_edited', 'expense_deleted', 'settlement', 'reminder'));--> statement-breakpoint
DROP TYPE "public"."notification_kind";
